services:
  appi:
    ports:
      - 3000:3000
    container_name: aws_api
    environment:
      - DATABASE_HOST=db-jose-augusto.cqih0bsinsto.us-east-1.rds.amazonaws.com
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Aula*infra
      - DATABASE_NAME=aws_db
      - DB_PORT=5432
    build:
      context: .
      dockerfile: Dockerfile